services:
  db:
    image: postgres:17
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_URL: ${DATABASE_URL}
    
